# Generated by Django 5.1.3 on 2025-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="account",
            field=models.CharField(default="00", max_length=15),
        ),
    ]
