# Generated by Django 5.1.3 on 2025-06-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employee_acc_source_alter_employee_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="contract_file",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="Address",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="acc_source",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="account",
            field=models.CharField(max_length=15),
        ),
    ]
