# Generated by Django 5.1.3 on 2025-06-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_employee_contract_file_employee_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Address",
            field=models.CharField(max_length=55),
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.employee",
                    ),
                ),
            ],
        ),
    ]
