# Generated by Django 5.2.1 on 2025-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_leave_leave_date_leave_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryslip",
            name="month",
            field=models.DateField(),
        ),
    ]
